 <link rel="stylesheet" href="{{asset('plugin/bootstrap/css/bootstrap.min.css')}}">
 <link rel="stylesheet" href="{{asset('plugin/font-awesome/css/font-awesome.min.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/style.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/style_details.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/style_tour.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/style_hotel.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/login.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/promotion.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/responsive.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/style_tour_region.css')}}">
 <link rel="stylesheet" href="{{asset('travel/css/news.css')}}">
  <link rel="stylesheet" href="{{asset('travel/css/owl.carousel.min.css')}}">
